### ISSUE TITLE
Cannot see other entities

### ISSUE THREAD

**Issue by BerntA** [BerntA/MasterSwordClassic#3]
Sometimes all entities are invisible and you have to kill in console to restore vision, why?

**Comment by greatguys1** [comment]
From Anonymouse,
_"This issue only happens if you are in the middle of the death screen and disconnect.
I've found out that it can only happen on dedicated servers, I've tested it in a local server and nothing happens.
It appears that entities only show up in the area where you died, everywhere else, they're invis, until of course if you die again.
Haven't really been able to pinpoint any part of the code being the culprit, though, but it's definitely server-sided. Changelevel does not work, but restarting the server, it goes back to normal again.
My assumption is that some flag or something is being set when you die, but isn't being reset when you respawn."_

I have also noted some of this throughout playing
